repos:
  - repo: local
    hooks:
      - id: format
        name: Format
        entry: make format
        language: system
        types: [python]
        pass_filenames: false
      - id: lint
        name: Linting
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false
